"""Generate armips pointer_redirect.asm from translate.build.json type=hook entries.

Layout (VMA):
  .org HOOK_STRING_POOL   — F9/PCS byte streams
  .org <pointer_slot>     — .word <label>  (rewrite pointer sources)

Shared UI literals often have many menu-table consumers while extract only
registers one pointer (e.g. nature-table sentinel for ``やめる``). When a
baserom is provided, pointer sites are expanded to every LE word that still
points at the entry body, then S5-filtered.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

# After FontChsSym (0x091E0000); before typical font_boundary file end.
HOOK_STRING_POOL = 0x09E00000
POINTER_BASE = 0x08000000
MIN_POINTER_SOURCE = 0x0


def _parse_addr(v: Any) -> int:
    if isinstance(v, int):
        return int(v)
    s = str(v).strip().replace("0x", "").replace("0X", "")
    return int(s, 16)


def _gba_addr(file_or_gba: int) -> int:
    a = int(file_or_gba)
    if a < POINTER_BASE:
        return a + POINTER_BASE
    return a


def _rom_offset(file_or_gba: int) -> int:
    a = int(file_or_gba)
    if a >= POINTER_BASE:
        return a - POINTER_BASE
    return a


def _hex_to_bytes(target_hex: str) -> bytes:
    raw = (target_hex or "").replace(" ", "").strip()
    if not raw:
        return b""
    return bytes.fromhex(raw)


def _byte_lines(data: bytes, indent: str = "  ") -> list[str]:
    lines: list[str] = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"{indent}.byte {hex_bytes}")
    return lines


def collect_hook_entries(entries: Iterable[dict]) -> list[dict]:
    out: list[dict] = []
    for e in entries:
        if (e.get("type") or "") != "hook":
            continue
        ptrs = e.get("pointer_sources") or []
        if not ptrs:
            continue
        blob = _hex_to_bytes(e.get("target_hex") or "")
        if not blob:
            continue
        if blob[-1] != 0xFF:
            blob = blob + b"\xFF"
        out.append({**e, "_blob": blob})
    return out


def _expand_hook_pointer_sources(
    rom: bytes | bytearray,
    entry: dict,
) -> list[int]:
    """Listed + discovered pointer file offsets for one hook body."""
    from .policy import expand_pointer_sources

    addr = entry.get("address")
    if addr is None:
        return [
            _rom_offset(_parse_addr(p))
            for p in (entry.get("pointer_sources") or [])
        ]
    return expand_pointer_sources(
        rom,
        _parse_addr(addr),
        entry.get("pointer_sources") or [],
        category=str(entry.get("module") or entry.get("category") or ""),
        original=str(entry.get("original") or ""),
        min_pointer_source=MIN_POINTER_SOURCE,
    )


def render_pointer_redirect_asm(
    hook_entries: list[dict],
    *,
    pool_org: int = HOOK_STRING_POOL,
    rom: bytes | bytearray | None = None,
) -> str:
    """Return asm text. Empty stub when no hook entries."""
    lines: list[str] = [
        "; auto-generated by meowth.pointer_redirect — do not edit",
        "; type=hook: string pool + pointer slot .word redirects",
        "",
    ]
    if not hook_entries:
        lines.append("; (no type=hook entries)")
        lines.append("")
        return "\n".join(lines)

    lines.append(f".org 0x{pool_org:08X}")
    lines.append(".align 4")
    lines.append("")

    labels: list[tuple[str, dict, list[int]]] = []
    for i, e in enumerate(hook_entries):
        label = f"hook_str_{i:04d}"
        eid = e.get("id") or ""
        mid = e.get("module") or ""
        if rom is not None:
            ptr_offs = _expand_hook_pointer_sources(rom, e)
        else:
            ptr_offs = []
            for p in e.get("pointer_sources") or []:
                off = _rom_offset(_parse_addr(p))
                if off >= MIN_POINTER_SOURCE:
                    ptr_offs.append(off)
        n_listed = len(e.get("pointer_sources") or [])
        extra = f" ptrs={len(ptr_offs)}"
        if rom is not None and len(ptr_offs) != n_listed:
            extra += f" (listed {n_listed}, expanded)"
        lines.append(f"; id={eid} module={mid}{extra}")
        lines.append(f"{label}:")
        lines.extend(_byte_lines(e["_blob"]))
        lines.append("")
        labels.append((label, e, ptr_offs))

    lines.append("; --- pointer redirects ---")
    lines.append("")
    for label, e, ptr_offs in labels:
        wrote = False
        for off in ptr_offs:
            if off < MIN_POINTER_SOURCE:
                continue
            gba = _gba_addr(off)
            lines.append(f".org 0x{gba:08X}")
            lines.append(f".word {label}")
            lines.append("")
            wrote = True
        if not wrote:
            lines.append(f"; WARN skipped {label}: no valid pointer_sources")
            lines.append("")

    return "\n".join(lines)


def write_pointer_redirect_asm(
    build_json_path: Path | None,
    out_path: Path,
    *,
    pool_org: int = HOOK_STRING_POOL,
    rom: bytes | bytearray | None = None,
    rom_path: Path | None = None,
) -> int:
    """Write asm from translate.build.json. Returns hook entry count."""
    entries: list[dict] = []
    if build_json_path and build_json_path.is_file():
        data = json.loads(build_json_path.read_text(encoding="utf-8"))
        entries = collect_hook_entries(data.get("entries") or [])
    rom_bytes = rom
    if rom_bytes is None and rom_path is not None and Path(rom_path).is_file():
        rom_bytes = Path(rom_path).read_bytes()
    text = render_pointer_redirect_asm(
        entries, pool_org=pool_org, rom=rom_bytes
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8", newline="\n")
    return len(entries)
