"""Generate armips translated_slot.asm from translate.build.json type=slot entries.

SlotTable layout (VMA):
  .org SLOT_TABLE_ADDR   — lookup table: jp_len | jp_hex | chinese_bytes FF
  sentinel: .byte 0

Each entry:
  jp_len(1B) | jp_bytes(jp_len) | chinese_bytes(... ending with 0xFF)

PrintNextChar reads this table at runtime: for each JP character encountered,
if its bytes match a slot entry, the Chinese replacement stream is drawn inline.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

# Must match game_addrs.asm SlotTableVMA / game.h ADDR_SLOT_TABLE
SLOT_TABLE_ADDR = 0x09EA0000

POINTER_BASE = 0x08000000


def _parse_addr(v: Any) -> int:
    if isinstance(v, int):
        return int(v)
    s = str(v).strip().replace("0x", "").replace("0X", "")
    return int(s, 16)


def _hex_to_bytes(target_hex: str) -> bytes:
    raw = (target_hex or "").replace(" ", "").strip()
    if not raw:
        return b""
    return bytes.fromhex(raw)


def _byte_lines(data: bytes, indent: str = "  ") -> list[str]:
    lines: list[str] = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"{indent}.byte {hex_bytes}")
    return lines


def collect_slot_entries(entries: Iterable[dict]) -> list[dict]:
    """Collect entries with type=slot that have valid JP and Chinese hex."""
    out: list[dict] = []
    for e in entries:
        if (e.get("type") or "") != "slot":
            continue
        jp_hex = e.get("original_hex") or ""
        target_hex = e.get("target_hex") or ""
        jp_bytes = _hex_to_bytes(jp_hex)
        chinese_bytes = _hex_to_bytes(target_hex)
        if not jp_bytes or not chinese_bytes:
            continue
        # Strip trailing 0xFF EOS from JP bytes — it's a terminator, not part of
        # the JP character sequence that PrintNextChar sees (each char is 1 call).
        while jp_bytes and jp_bytes[-1] == 0xFF:
            jp_bytes = jp_bytes[:-1]
        if not jp_bytes:
            continue
        # Ensure Chinese stream ends with 0xFF (EOS)
        if chinese_bytes[-1] != 0xFF:
            chinese_bytes = chinese_bytes + b"\xFF"
        out.append({**e, "_jp_bytes": jp_bytes, "_chinese_bytes": chinese_bytes})
    return out


def render_slot_table_asm(
    slot_entries: list[dict],
    *,
    table_org: int = SLOT_TABLE_ADDR,
) -> str:
    """Return asm text for the slot lookup table. Empty stub when no entries."""
    lines: list[str] = [
        "; auto-generated by meowth.translated_slot — do not edit",
        "; type=slot: JP hex → Chinese replacement lookup table",
        "",
    ]
    if not slot_entries:
        lines.append("; (no type=slot entries)")
        lines.append("")
        return "\n".join(lines)

    lines.append(f".org 0x{table_org:08X}")
    lines.append(".align 4")
    lines.append("SlotTable:")

    for e in slot_entries:
        jp_bytes = e["_jp_bytes"]
        chinese_bytes = e["_chinese_bytes"]
        eid = e.get("id") or ""
        mid = e.get("module") or ""

        # Build entry: jp_len, jp_bytes..., chinese_bytes...
        entry_bytes = bytes([len(jp_bytes)]) + jp_bytes + chinese_bytes
        hex_parts = ", ".join(f"0x{b:02X}" for b in entry_bytes)
        lines.append(f"  ; id={eid} module={mid} jp_len={len(jp_bytes)}")
        lines.append(f"  .byte {hex_parts}")

    lines.append("  .byte 0  ; end sentinel")
    lines.append("")
    return "\n".join(lines)


def write_slot_table_asm(
    build_json_path: Path | None,
    out_path: Path,
    *,
    table_org: int = SLOT_TABLE_ADDR,
    rom: bytes | bytearray | None = None,
    rom_path: Path | None = None,
) -> int:
    """Write asm from translate.build.json. Returns slot entry count."""
    entries: list[dict] = []
    if build_json_path and build_json_path.is_file():
        data = json.loads(build_json_path.read_text(encoding="utf-8"))
        entries = collect_slot_entries(data.get("entries") or [])
    text = render_slot_table_asm(entries, table_org=table_org)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8", newline="\n")
    return len(entries)
