"""Generate armips translated_slot.asm — FNV-1a hash keyed.

v2 layout（首字节分桶，本模块生成，hook/src/text/PrintNextChar_hook.c 消费）：

  Header (.align 4):
    u32 magic 'SLT2' = 0x32544C53
    u32 n_buckets(u16 LE) | max_jp_len(u16 LE)   （打包进一个 word）
    u32 bucket_offset[n_buckets + 1]             （相对 SlotTable 标签的字节偏移）
  Entries（按 jp_bytes[0] 分桶组排放；桶内保持原顺序 → 匹配语义与 v1 一致）：
    key(4B FNV1a(jp)) | jp_len_le16(2B) | jp_bytes | chinese_bytes(... 0xFF)

运行时：cur_char 直接定位桶 → 只遍历桶内条目；流窗口以 max_jp_len 封顶；
增量 FNV 前缀哈希 ph[len] 与条目 key 直接比对（v1 是每条重哈希）。
801 条 / ~94 个首字节 / 最大桶 ~43 条 → 每字符查找成本约降三个数量级。

Legacy 平铺布局（key|len|jp|cn … 4x00 哨兵）仍被 runtime hook 支持：
magic 不匹配时自动回退线性查找，兼容旧表/回滚。
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

SLOT_TABLE_ADDR = 0x09EA0000
SLOT_TABLE_MAGIC = 0x32544C53  # 'SLT2'
SLOT_TABLE_N_BUCKETS = 256


def _fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def _hex_to_bytes(s: str) -> bytes:
    raw = (s or "").replace(" ", "").strip()
    return bytes.fromhex(raw) if raw else b""


def collect_slot_entries(entries: Iterable[dict]) -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for e in entries:
        if e.get("type") != "slot":
            continue
        jp = _hex_to_bytes(e.get("original_hex") or "")
        cn = _hex_to_bytes(e.get("target_hex") or "")
        if not jp or not cn:
            continue
        while jp and jp[-1] == 0xFF:
            jp = jp[:-1]
        if not jp:
            continue
        if cn[-1] != 0xFF:
            cn = cn + b"\xFF"
        key = jp.hex()
        if key in seen:
            continue
        seen.add(key)
        out.append({**e, "_jp": jp, "_cn": cn})
    return out


def render_slot_table_asm(entries: list[dict], *, org: int = SLOT_TABLE_ADDR) -> str:
    # 逐条编码（与 v1 条目编码完全一致），并按首字节分桶（保持原表相对顺序）
    bucket_items: list[list[tuple[bytes, bytes]]] = [[] for _ in range(SLOT_TABLE_N_BUCKETS)]
    max_jp_len = 1
    for e in entries:
        jp, cn = e["_jp"], e["_cn"]
        bucket_items[jp[0]].append((jp, cn))
        max_jp_len = max(max_jp_len, len(jp))

    buckets: list[list[bytes]] = [[] for _ in range(SLOT_TABLE_N_BUCKETS)]
    for b, items in enumerate(bucket_items):
        for jp, cn in sorted(items, key=lambda pair: len(pair[0]), reverse=True):
            h = _fnv1a(jp)
            kb = h.to_bytes(4, "little")
            lb = len(jp).to_bytes(2, "little")
            buckets[b].append(kb + lb + jp + cn)

    # 桶偏移表：header 之后依次排放各桶；offsets 相对 SlotTable 标签
    header_size = 8 + 4 * (SLOT_TABLE_N_BUCKETS + 1)
    offsets: list[int] = []
    cur = header_size
    for b in range(SLOT_TABLE_N_BUCKETS):
        offsets.append(cur)
        cur += sum(len(blob) for blob in buckets[b])
    offsets.append(cur)  # 末哨兵 = 桶区结束

    lines = [
        "; auto-generated by translated_slot — do not edit",
        "; v2 bucketed: magic | n_bkts<<0/maxlen<<16 | offsets[n+1] | entries",
        "; entry: key(4B) | jp_len_le16(2B) | jp_bytes | chinese_bytes(... 0xFF)",
        "",
        f".org 0x{org:08X}",
        ".align 4",
        "SlotTable:",
        f"  .word 0x{SLOT_TABLE_MAGIC:08X}  ; 'SLT2'",
        f"  .word 0x{((max_jp_len << 16) | SLOT_TABLE_N_BUCKETS):08X}"
        f"  ; n_buckets={SLOT_TABLE_N_BUCKETS}, max_jp_len={max_jp_len}",
    ]
    for k in range(0, SLOT_TABLE_N_BUCKETS + 1, 4):
        chunk = offsets[k:k + 4]
        lines.append(
            "  .word " + ", ".join(f"0x{o:08X}" for o in chunk)
            + f"  ; bucket offsets {k}..{k + len(chunk) - 1}"
        )
    for b, blobs in enumerate(buckets):
        if not blobs:
            continue
        lines.append(f"; bucket 0x{b:02X} ({len(blobs)} entries)")
        for blob in blobs:
            lines.append(f"  .byte {', '.join(f'0x{byte:02X}' for byte in blob)}")
    lines.append("")
    return "\n".join(lines)


def write_slot_table_asm(
    build_json_path: Path | None, out_path: Path, *, org: int = SLOT_TABLE_ADDR,
    **_: Any,
) -> int:
    entries: list[dict] = []
    if build_json_path and build_json_path.is_file():
        data = json.loads(build_json_path.read_text(encoding="utf-8"))
        entries = collect_slot_entries(data.get("entries") or [])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_slot_table_asm(entries, org=org), encoding="utf-8", newline="\n")
    return len(entries)
