"""Generate armips translated_slot.asm — FNV-1a hash keyed.

Format per entry: key(4B) | jp_len(1B) | jp_bytes(jp_len) | chinese_bytes(... 0xFF)
Sentinel: 4 bytes 0x00.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

SLOT_TABLE_ADDR = 0x09EA0000


def _fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def _hex_to_bytes(s: str) -> bytes:
    raw = (s or "").replace(" ", "").strip()
    return bytes.fromhex(raw) if raw else b""


def collect_slot_entries(entries: Iterable[dict]) -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for e in entries:
        if e.get("type") != "slot":
            continue
        jp = _hex_to_bytes(e.get("original_hex") or "")
        cn = _hex_to_bytes(e.get("target_hex") or "")
        if not jp or not cn:
            continue
        while jp and jp[-1] == 0xFF:
            jp = jp[:-1]
        if not jp:
            continue
        if cn[-1] != 0xFF:
            cn = cn + b"\xFF"
        key = jp.hex()
        if key in seen:
            continue
        seen.add(key)
        out.append({**e, "_jp": jp, "_cn": cn})
    return out


def render_slot_table_asm(entries: list[dict], *, org: int = SLOT_TABLE_ADDR) -> str:
    lines = [
        "; auto-generated by translated_slot — do not edit",
        "; key(4B) | jp_len(1B) | jp_bytes | chinese_bytes(... 0xFF)",
        "",
        f".org 0x{org:08X}",
        ".align 4",
        "SlotTable:",
    ]
    for e in entries:
        jp, cn = e["_jp"], e["_cn"]
        h = _fnv1a(jp)
        kb = h.to_bytes(4, "little")
        entry = kb + bytes([len(jp)]) + jp + cn
        lines.append(f"  .byte {', '.join(f'0x{b:02X}' for b in entry)}")
    lines += ["  .byte 0,0,0,0  ; sentinel", ""]
    return "\n".join(lines)


def write_slot_table_asm(
    build_json_path: Path | None, out_path: Path, *, org: int = SLOT_TABLE_ADDR,
    **_: Any,
) -> int:
    entries: list[dict] = []
    if build_json_path and build_json_path.is_file():
        data = json.loads(build_json_path.read_text(encoding="utf-8"))
        entries = collect_slot_entries(data.get("entries") or [])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_slot_table_asm(entries, org=org), encoding="utf-8", newline="\n")
    return len(entries)
